/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(main)/': RouteRecordInfo<'/(main)/', '/(main)', Record<never, never>, Record<never, never>>,
    '/(main)/dashboard': RouteRecordInfo<'/(main)/dashboard', '/(main)/dashboard', Record<never, never>, Record<never, never>>,
    '/(main)/nav/1/item-1': RouteRecordInfo<'/(main)/nav/1/item-1', '/(main)/nav/1/item-1', Record<never, never>, Record<never, never>>,
    '/(main)/nav/2': RouteRecordInfo<'/(main)/nav/2', '/(main)/nav/2', Record<never, never>, Record<never, never>>,
    '/(main)/nav/4': RouteRecordInfo<'/(main)/nav/4', '/(main)/nav/4', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
